Repository fusionjs/browser-tests, pull requests merged in 2018-11, with the labels that each got.

#166 Update script to exit immediately when a test step fails
  .buildkite/run-all-tests.sh
  test-remotely.sh
Labels: bugfix

#172 Improve CI
  .buildkite/pipeline.yml
  .buildkite/run-all-tests.sh
  docker-compose-node-last.yml
  docker-compose.yml
  nightwatch-ci.js
  selenium-environments.js
  src/.DS_Store
  src/test/browser/index.js
  test-remotely.sh
Labels: refactor

#173 Update browsers
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
  package.json
  selenium-environments.js
  test-remotely.sh
  yarn.lock
Labels: feature
